### ISSUE TITLE
Can't install this pacakge

### ISSUE THREAD

**Issue by ChenlingTangMDA** [pekjoonwu/CELINA#1]
Hi, 

The CELINE package can't install with devtools::install_github("pekjoonwu/CELINA"), No response.
Or,  through devtools::install_local("CELINA-master.zip") with error, Error in rawToChar(block[seq_len(ns)])

**Comment by ChenlingTangMDA** [comment]
The package were smoothly install under R4.4, but failing with R4.1

**Comment by pekjoonwu** [comment]
Hi @ChenlingTangMDA ,

Thank you very much for your interest in our package and for your detailed feedback.

We are pleased to hear that it works well under R 4.4. It appears that some of our dependencies (R packages) require R version 4.4 or higher. We will update the dependencies to ensure compatibility with older versions of R. Thank you for bringing this to our attention!

Best,
Peijun
